/**
 * AUTO-GENERATED by frontend/scripts/gen-api.ts. DO NOT EDIT BY HAND.
 * Regenerate via `pnpm gen:api`.
 */
export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Return the liveness envelope ``{"ok": true}``.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Validate credentials and return a JWT.
         *
         *     Wrong credentials raise 401 `invalid_credentials`; oversized payloads
         *     are rejected with 422 by Pydantic before this handler runs. Repeated
         *     failures from the same (username, client_ip) bucket trip a 429
         *     ``too_many_attempts`` brake.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the authenticated user.
         *
         *     Used by the SPA on boot to validate a persisted token. The dep takes
         *     care of 401 paths — by the time we reach the body, `current_user` is
         *     guaranteed to be a real row.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List cards
         * @description Return cards matching the query filters. Default sort is ``created_at DESC, id DESC``. Archived cards are excluded unless ``include_archived=true`` is passed.
         */
        get: operations["list_cards_api_v1_cards_get"];
        put?: never;
        /** Publish a new card */
        post: operations["publish_card_api_v1_cards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a card by id */
        put: operations["update_card_api_v1_cards__card_id__put"];
        post?: never;
        /** Delete a card */
        delete: operations["delete_card_api_v1_cards__card_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cards/{card_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Archive or unarchive a card */
        patch: operations["archive_card_api_v1_cards__card_id__archive_patch"];
        trace?: never;
    };
    "/api/v1/cards/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get card by slug */
        get: operations["get_card_api_v1_cards__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/covers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a cover image for a card
         * @description Validate the multipart upload and persist it for ``card_id``.
         */
        post: operations["post_cover_api_v1_covers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Return the liveness envelope ``{"ok": true}``.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List distinct tags
         * @description Return the distinct union of card tags, case-insensitively deduped and sorted. By default, tags from archived cards are excluded; pass ``include_archived=true`` to include them.
         */
        get: operations["get_tags_api_v1_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_post_cover_api_v1_covers_post */
        Body_post_cover_api_v1_covers_post: {
            /**
             * Card Id
             * Format: uuid
             */
            card_id: string;
            /** File */
            file: string;
        };
        /**
         * CardArchive
         * @description Setter for the archive endpoint. ``archived`` is required (no default).
         *
         *     Removing the legacy "empty body archives" surprise from phase 1 is the
         *     whole point of the explicit required field.
         */
        CardArchive: {
            /** Archived */
            archived: boolean;
        };
        /**
         * CardCreate
         * @description Admin publish payload.
         *
         *     Validates ``external ⇒ url`` and ``local ⇒ body`` after the field-level
         *     coercions run, so a payload with both/neither is rejected before the
         *     service is invoked.
         */
        CardCreate: {
            /** Body */
            body?: string | null;
            /**
             * Category
             * @enum {string}
             */
            category: "external" | "local";
            /** Cover */
            cover?: string | null;
            /** Group */
            group?: ("技术类" | "随笔类" | "生活类") | null;
            /** Slug */
            slug?: string | null;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Tags */
            tags?: string[];
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
        };
        /**
         * CardDetail
         * @description Detail read shape including raw body and rendered HTML.
         *
         *     ``body`` and ``body_html`` are only populated when ``category == 'local'``
         *     so external cards stay light over the wire.
         */
        CardDetail: {
            /**
             * Archived
             * @default false
             */
            archived: boolean;
            /** Body */
            body?: string | null;
            /** Body Html */
            body_html?: string | null;
            /**
             * Category
             * @enum {string}
             */
            category: "external" | "local";
            /** Cover */
            cover?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Group */
            group?: ("技术类" | "随笔类" | "生活类") | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Tags */
            tags?: string[];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Url */
            url?: string | null;
        };
        /**
         * CardListItem
         * @description List-row projection of a card. Used by ``GET /cards``.
         */
        CardListItem: {
            /**
             * Archived
             * @default false
             */
            archived: boolean;
            /**
             * Category
             * @enum {string}
             */
            category: "external" | "local";
            /** Cover */
            cover?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Group */
            group?: ("技术类" | "随笔类" | "生活类") | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Tags */
            tags?: string[];
            /** Title */
            title: string;
        };
        /**
         * CardRead
         * @description Full read shape minus body/body_html. Returned by archive endpoint.
         */
        CardRead: {
            /**
             * Archived
             * @default false
             */
            archived: boolean;
            /**
             * Category
             * @enum {string}
             */
            category: "external" | "local";
            /** Cover */
            cover?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Group */
            group?: ("技术类" | "随笔类" | "生活类") | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Tags */
            tags?: string[];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Url */
            url?: string | null;
        };
        /**
         * CardUpdate
         * @description Admin partial update payload.
         *
         *     Every field is optional. Omitted fields are preserved by the service so a
         *     PUT with only ``{title: '…'}`` no longer wipes ``summary``/``cover`` — a
         *     fix for a documented P1 bug from phase 1.
         *
         *     The category/url/body coupling is re-checked against the merged result in
         *     the service layer, since this schema cannot see the current row.
         */
        CardUpdate: {
            /** Body */
            body?: string | null;
            /** Category */
            category?: ("external" | "local") | null;
            /** Cover */
            cover?: string | null;
            /** Group */
            group?: ("技术类" | "随笔类" | "生活类") | null;
            /** Slug */
            slug?: string | null;
            /** Summary */
            summary?: string | null;
            /** Tags */
            tags?: string[] | null;
            /** Title */
            title?: string | null;
            /** Url */
            url?: string | null;
        };
        /**
         * CoverUploadResponse
         * @description Response body for ``POST /api/v1/covers``.
         *
         *     Attributes:
         *         ok: Constant ``True`` so success/failure can be branched on a single
         *             field without inspecting status codes.
         *         url: Public URL of the stored cover (``COVERS_PUBLIC_PREFIX`` +
         *             ``/{card_id}.{ext}`` + cache-buster ``?v=<unix-ts>``).
         *         width: Decoded pixel width (post-Pillow verify).
         *         height: Decoded pixel height.
         *         bytes: Final on-disk size in bytes.
         *         card: The updated card row, projected through :class:`CardRead`.
         */
        CoverUploadResponse: {
            /** Bytes */
            bytes: number;
            card: components["schemas"]["CardRead"];
            /** Height */
            height: number;
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
            /** Url */
            url: string;
            /** Width */
            width: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LoginRequest
         * @description Body of `POST /api/v1/auth/login`.
         *
         *     Bounds match the user table widths in §3.3 so over-long inputs are
         *     rejected with a 422 before they reach bcrypt (which itself truncates at
         *     72 bytes).
         */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * OkResponse
         * @description Shape of the bare-acknowledgement success response.
         */
        OkResponse: {
            /**
             * Ok
             * @default true
             * @constant
             */
            ok: true;
        };
        /**
         * TokenResponse
         * @description Success body of `POST /api/v1/auth/login`.
         *
         *     `expires_in` is seconds, mirroring the conventional OAuth2 token
         *     response shape so the frontend can store an absolute deadline if it
         *     wants to.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            user: components["schemas"]["UserRead"];
        };
        /**
         * UserRead
         * @description Public read view of a user row.
         */
        UserRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cards_api_v1_cards_get: {
        parameters: {
            query?: {
                category?: ("external" | "local") | null;
                group?: ("技术类" | "随笔类" | "生活类") | null;
                tag?: string | null;
                q?: string | null;
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_card_api_v1_cards_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_card_api_v1_cards__card_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_card_api_v1_cards__card_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_card_api_v1_cards__card_id__archive_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                card_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardArchive"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_card_api_v1_cards__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_cover_api_v1_covers_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_post_cover_api_v1_covers_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    get_tags_api_v1_tags_get: {
        parameters: {
            query?: {
                /** @description Include tags attached to archived cards. */
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
