/**
 * AUTO-GENERATED by frontend/scripts/gen-api.ts. DO NOT EDIT BY HAND.
 * Regenerate via `pnpm gen:api`.
 */
export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health (stable monitor path) */
        get: operations["health_root"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: operations["auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List cards */
        get: operations["list_cards"];
        put?: never;
        /** Create card */
        post: operations["create_card"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update card */
        put: operations["update_card"];
        post?: never;
        /** Delete card */
        delete: operations["delete_card"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cards/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Archive card */
        patch: operations["archive_card"];
        trace?: never;
    };
    "/api/v1/cards/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get card by slug */
        get: operations["get_card"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/covers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload cover */
        post: operations["upload_cover"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health (v1 mirror) */
        get: operations["health_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tags */
        get: operations["list_tags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CardArchive */
        CardArchive: {
            archived: boolean;
        };
        /** CardCreate */
        CardCreate: {
            body?: string | null;
            /** @enum {string} */
            category: "external" | "local";
            cover?: string | null;
            /** @enum {string|null} */
            group?: "技术类" | "随笔类" | "生活类" | null;
            slug?: string | null;
            /** @default  */
            summary: string;
            /** @default [] */
            tags: string[];
            title: string;
            url?: string | null;
        };
        /** CardDetail */
        CardDetail: {
            archived: boolean;
            body?: string | null;
            body_html?: string | null;
            /** @enum {string} */
            category: "external" | "local";
            cover?: string | null;
            /** Format: date-time */
            created_at: string;
            /** @enum {string|null} */
            group?: "技术类" | "随笔类" | "生活类" | null;
            /** Format: uuid */
            id: string;
            slug: string;
            summary: string;
            tags: string[];
            title: string;
            /** Format: date-time */
            updated_at: string;
            url?: string | null;
        };
        /** CardListItem */
        CardListItem: {
            archived: boolean;
            /** @enum {string} */
            category: "external" | "local";
            cover?: string | null;
            /** Format: date-time */
            created_at: string;
            /** @enum {string|null} */
            group?: "技术类" | "随笔类" | "生活类" | null;
            /** Format: uuid */
            id: string;
            slug: string;
            summary: string;
            tags: string[];
            title: string;
        };
        /** CardRead */
        CardRead: {
            archived: boolean;
            /** @enum {string} */
            category: "external" | "local";
            cover?: string | null;
            /** Format: date-time */
            created_at: string;
            /** @enum {string|null} */
            group?: "技术类" | "随笔类" | "生活类" | null;
            /** Format: uuid */
            id: string;
            slug: string;
            summary: string;
            tags: string[];
            title: string;
            /** Format: date-time */
            updated_at: string;
            url?: string | null;
        };
        /** CardUpdate */
        CardUpdate: {
            body?: string | null;
            /** @enum {string} */
            category?: "external" | "local";
            cover?: string | null;
            /** @enum {string|null} */
            group?: "技术类" | "随笔类" | "生活类" | null;
            slug?: string | null;
            summary?: string;
            tags?: string[];
            title?: string;
            url?: string | null;
        };
        /** CoverUploadResponse */
        CoverUploadResponse: {
            bytes: number;
            card: components["schemas"]["CardRead"];
            height: number;
            /** @constant */
            ok: true;
            url: string;
            width: number;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            code: string;
            detail?: Record<string, never>[] | null;
            error: string;
            /** @constant */
            ok: false;
        };
        /** LoginRequest */
        LoginRequest: {
            password: string;
            username: string;
        };
        /** OkResponse */
        OkResponse: {
            /** @constant */
            ok: true;
        };
        /** TokenResponse */
        TokenResponse: {
            access_token: string;
            expires_in: number;
            /** @constant */
            token_type: "bearer";
            user: components["schemas"]["UserRead"];
        };
        /** UserRead */
        UserRead: {
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            id: string;
            role: string;
            username: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_root: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    list_cards: {
        parameters: {
            query?: {
                category?: "external" | "local" | null;
                group?: "技术类" | "随笔类" | "生活类" | null;
                tag?: string | null;
                q?: string | null;
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardListItem"][];
                };
            };
        };
    };
    create_card: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDetail"];
                };
            };
        };
    };
    update_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDetail"];
                };
            };
        };
    };
    delete_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    archive_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardArchive"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardRead"];
                };
            };
        };
    };
    get_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    upload_cover: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: uuid */
                    card_id: string;
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverUploadResponse"];
                };
            };
        };
    };
    health_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    list_tags: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
}
