#!/usr/bin/env node
/**
 * gen-api.ts — pull the backend OpenAPI document and regenerate typed clients.
 *
 * Usage:
 *   tsx scripts/gen-api.ts                          # auto-detect (live -> snapshot)
 *   API_BASE=http://127.0.0.1:5001 tsx scripts/...  # override backend root
 *   tsx scripts/gen-api.ts --offline                # never touch the network
 *
 * Steps:
 *   1. Try GET <API_BASE>/api/v1/openapi.json. On success, write a deterministic,
 *      pretty-printed copy to openapi/schema.json (the committed snapshot).
 *   2. If the backend is unreachable (or --offline was passed), fall back to the
 *      existing openapi/schema.json on disk.
 *   3. Run openapi-typescript over the JSON and write src/shared/api/schema.d.ts.
 *
 * CI gate: `pnpm gen:api && git diff --exit-code openapi/schema.json
 *           src/shared/api/schema.d.ts` — a non-empty diff means a developer
 * forgot to regenerate after a backend change.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const ROOT = resolve(__dirname, '..')

const SNAPSHOT_PATH = resolve(ROOT, 'openapi/schema.json')
const DTS_PATH = resolve(ROOT, 'src/shared/api/schema.d.ts')

const API_BASE = process.env.API_BASE ?? 'http://127.0.0.1:5001'
const OFFLINE = process.argv.includes('--offline') || process.env.LG_OFFLINE === '1'

type JsonObject = Record<string, unknown>

function sortKeys<T>(value: T): T {
  if (Array.isArray(value)) return value.map(sortKeys) as unknown as T
  if (value !== null && typeof value === 'object') {
    const sorted: JsonObject = {}
    const obj = value as JsonObject
    for (const key of Object.keys(obj).sort()) {
      sorted[key] = sortKeys(obj[key])
    }
    return sorted as unknown as T
  }
  return value
}

async function fetchLiveSchema(): Promise<JsonObject | null> {
  if (OFFLINE) return null
  const url = `${API_BASE}/api/v1/openapi.json`
  try {
    const controller = new AbortController()
    const timer = setTimeout(() => controller.abort(), 3000)
    const res = await fetch(url, { signal: controller.signal })
    clearTimeout(timer)
    if (!res.ok) {
      console.warn(`[gen-api] backend returned ${res.status} from ${url}; falling back`)
      return null
    }
    return (await res.json()) as JsonObject
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    console.warn(`[gen-api] could not reach ${url}: ${message}; falling back`)
    return null
  }
}

function loadSnapshot(): JsonObject {
  try {
    const raw = readFileSync(SNAPSHOT_PATH, 'utf-8')
    return JSON.parse(raw) as JsonObject
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    throw new Error(
      `[gen-api] no live schema and snapshot at ${SNAPSHOT_PATH} is unreadable: ${message}`,
    )
  }
}

async function main(): Promise<void> {
  const live = await fetchLiveSchema()
  const schema = live ?? loadSnapshot()

  // Persist a deterministic snapshot (sorted keys + trailing newline).
  if (live) {
    mkdirSync(dirname(SNAPSHOT_PATH), { recursive: true })
    writeFileSync(SNAPSHOT_PATH, JSON.stringify(sortKeys(schema), null, 2) + '\n', 'utf-8')
    console.log(`[gen-api] wrote snapshot -> ${SNAPSHOT_PATH}`)
  } else {
    console.log(`[gen-api] using committed snapshot -> ${SNAPSHOT_PATH}`)
  }

  const ast = await openapiTS(schema)
  const ts = astToString(ast)
  const banner =
    '/**\n * AUTO-GENERATED by frontend/scripts/gen-api.ts. DO NOT EDIT BY HAND.\n' +
    ' * Regenerate via `pnpm gen:api`.\n */\n'
  mkdirSync(dirname(DTS_PATH), { recursive: true })
  writeFileSync(DTS_PATH, banner + ts, 'utf-8')
  console.log(`[gen-api] wrote types -> ${DTS_PATH}`)
}

main().catch((err: unknown) => {
  const message = err instanceof Error ? err.message : String(err)
  console.error(`[gen-api] fatal: ${message}`)
  process.exit(1)
})
